### ISSUE TITLE
error: queryHandler: no querying endpoint provided

### ISSUE THREAD

**Issue by licsuj27** [ricardbejarano/graphql_exporter#4]
Hi,
 So I'm following the example listed as part of the prometheus.yml configuration.
 
```
{
                  viewer {
                    zones(filter: {zoneTag: "abc123"}) {
                      httpRequests1mGroups(limit: 1, filter: { datetime_gt: "2021-04-28T13:00:00Z", datetime_lt: "2021-04-28T14:01:00Z"}) {
                        dimensions {
                          datetime
                        }
                        sum {
                          bytes
                        }
                      }
                    }
                  }
                }
```
                
  Executing the above on a graphQL application, it works successfully and returns correct values, however as part of the prometheus configuration I'm getting error on graphql_exporter  - error: queryHandler: no querying endpoint provided>
  
  Can you kindly indicate me if i'm missing something

**Comment by ricardbejarano** [comment]
Sure!

---

You're missing the `endpoint` parameter on your scrape config:

```yaml
scrape_configs:
  - job_name: "graphql-exporter"
    metrics_path: "/query"
    params:
      endpoint: ["< your api graphql endpoint url >"]  # you're missing this
      query:
        - "< your query >"
```

You must specify at least one endpoint, or else `graphql_exporter` doesn't know where to send the query to.

Lemme know if it helped!
